Lesson 1
FidelSol/geekshop_server pull request #1
Opened 2021-08-12 08:24 UTC by FidelSol

Урок 1

2021-08-12 09:55 UTC, Vokler requested changes
Так же не совсем понял, зачем в репозитории файлы Pipfile и Pipfile.lock?

Так же у вас в репозитории не должны находиться файлы/каталоги: .idea, db.sqlite3, pycache.
Алгоритм удаления каталога/файла из репозитория:
1. Удаляете из .gitignore файлы, которые игнорируются (потому что git вообще их не видит и даже, если вы удаляете эти файл из проекта, git продолжает игнорировать любые действия с этими фалами);
2. Удаляете сами файлы из проекта;
3. Делаете git push;
4. Обратно возвращаете в .gitignore файлы, которые нужно игнорировать;
5. Делаете git push

2021-08-12 09:55 UTC, Vokler commented on products/urls.py
> +    re_path(r'^contact/$', views.contact, name='contact'),
Вы использовали регулярные выражения для объявление путей - так можно, но это в старой версии так в основном делали.
Сейчас можно использовать path(), как мы это делали на уроке

2021-08-12 15:20 UTC, FidelSol commented on products/urls.py
> +    re_path(r'^contact/$', views.contact, name='contact'),
Pipfile для загрузки командой pipenv sync всех пакетов проекта при разворачивании с репозитория
Внутри папки .idea у меня только остался ее стандартный .gitignore - сейчас уберу и ее
db.sqlite3 и pycache у меня указаны в основном .gitignore и их нет в репозитории

2021-08-13 10:31 UTC, Vokler commented on products/urls.py
> +    re_path(r'^contact/$', views.contact, name='contact'),
Хорошо, напишите пожалуйста, как уберете .idea

2021-08-15 21:52 UTC, FidelSol commented on products/urls.py
> +    re_path(r'^contact/$', views.contact, name='contact'),
Здравстуйте! Я исправил .gitignore

2021-08-16 10:52 UTC, Vokler approved these changes

2021-08-16 10:52 UTC, merged