Lesson 2
FidelSol/geekshop_server pull request #2
Opened 2021-08-16 16:42 UTC by FidelSol

2021-08-17 12:21 UTC, Vokler requested changes

2021-08-17 12:21 UTC, Vokler commented on products/fixtures/products.json
> +        "title": "GeekShop - каталог",
В json файле не нужно хранить весь контекст, а только список продуктов. json файл в этом случае пока выступает у нас некой БД. А такие переменные как title лучше держать непосредственно в context

2021-08-19 06:59 UTC, FidelSol commented on products/fixtures/products.json
> +        "title": "GeekShop - каталог",
Исправил json и title во вьюшке

2021-08-19 10:49 UTC, Vokler approved these changes

2021-08-19 10:49 UTC, merged