Lesson 3
FidelSol/geekshop_server pull request #3
Opened 2021-08-20 10:28 UTC by FidelSol

Lesson 3

2021-08-20 10:45 UTC, Vokler requested changes

2021-08-20 10:45 UTC, Vokler commented on products/models.py
> +    name = models.CharField('Название', max_length=64, unique=True)
Если вы везде в классе используете название атрибутов `max_length=64, unique=True`, то и для 'Название' тоже лучше использовать. То же самое и в других классах.

2021-08-20 10:45 UTC, Vokler commented on products/views.py
> +    context = {'title': 'GeekShop - Продукты', "categories": catedories, "products": products}
Придерживайтесь везде единого стиля кавычек

2021-08-23 07:25 UTC, FidelSol commented on products/models.py
> +    name = models.CharField('Название', max_length=64, unique=True)
Исправил

2021-08-23 07:25 UTC, FidelSol commented on products/views.py
> +    context = {'title': 'GeekShop - Продукты', "categories": catedories, "products": products}
Исправил

2021-08-23 09:21 UTC, merged